version: "3"
services:
  dangmoog:
    image: chat
    build:
      context: . # microservice를 제작할 폴더 지정
      dockerfile: Dockerfile
    container_name: chat # 생성될 때 생기는 이름
    ports:
      - "2024:2024" # 외부 포트:컨테이너 포트
    environment:
      - SQLALCHEMY_DATABASE_URL=
      - ACCESS_TOKEN_HASH=
      - TZ=Asia/Seoul
    restart: "always"

